# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('pic_url', models.URLField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'news',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_type', models.CharField(choices=[('text', 'Text'), ('news', 'Multi pics'), ('music', 'Music'), ('action', 'Action')], max_length=10)),
                ('text_reply', models.TextField(blank=True)),
                ('music_title', models.CharField(blank=True, max_length=40)),
                ('music_description', models.CharField(blank=True, max_length=40)),
                ('music_url', models.URLField(blank=True)),
                ('music_hq_url', models.URLField(blank=True)),
                ('action', models.CharField(blank=True, max_length=30)),
                ('parameter', models.CharField(blank=True, max_length=20)),
                ('news_reply', models.ManyToManyField(blank=True, to='auto_reply.News')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_reply.Reply'),
        ),
    ]
