# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssacount', '0006_auto_20160224_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssacount',
            name='url',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
