# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSAcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinetip', models.GenericIPAddressField()),
                ('time', models.TimeField()),
                ('retserver', models.CharField(max_length=50)),
            ],
        ),
    ]
