# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20160229_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='clinetip',
            field=models.GenericIPAddressField(default=None),
        ),
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.TimeField(default=None),
        ),
    ]
