# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20160229_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(default=None),
        ),
    ]
