# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20160229_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
